# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Update Project Status Based on Label

on:
  label:
    types: [created, removed]
  issues:
    types: [labeled, unlabeled]
  pull_request:
    types: [labeled, unlabeled]

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        uses: cli/cli-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine project column based on label
        id: determine-column
        run: |
          LABEL=${{ github.event.label.name }}
          if [[ "$LABEL" == "bug" ]]; then
            echo "column=Security" >> $GITHUB_ENV
          elif [[ "$LABEL" == "feature-request" ]]; then
            echo "column=Enhancement" >> $GITHUB_ENV
          else
            echo "column=Backlog" >> $GITHUB_ENV
          fi

      - name: Update project column
        run: |
          gh api -X PATCH /repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/projects \
            -f project_column="${{ env.column }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

