# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Update Issue Project Status and Add to Project

on:
  issues:
    types: [labeled]

jobs:
  update-project-status:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Add to Project
        uses: actions/add-to-project@main
        id: addItem
        with:
          project-url: https://github.com/orgs/TheNewestFactor/projects/8
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: bug, feature-request, other  # Add any other labels as required
          label-operator: OR

      - name: Determine Project Status
        id: determine-status
        run: |
          LABEL=${{ github.event.label.name }}
          if [ "$LABEL" = "bug" ]; then
            echo "status=Security" >> $GITHUB_ENV
          elif [ "$LABEL" = "feature-request" ]; then
            echo "status=Enhancement" >> $GITHUB_ENV
          else
            echo "status=Backlog" >> $GITHUB_ENV

      - name: Update Project Item Status
        uses: kalgurn/update-project-item-status@main
        with:
          project-url: https://github.com/orgs/TheNewestFactor/projects/8
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          item-id: ${{ steps.addItem.outputs.itemId }}
          status: ${{ env.status }}
