# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Update Issue Project Status

on:
  issues:
    types: [labeled]

jobs:
  update-project-status:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Update Project Status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LABEL=${{ github.event.label.name }}
          ISSUE_NUMBER=${{ github.event.issue.number }}
          REPO=${{ github.repository }}

          if [ "$LABEL" = "bug" ]; then
            STATUS="Security"
          elif [ "$LABEL" = "feature-request" ]; then
            STATUS="Enhancement"
          else
            STATUS="Backlog"
          fi

          echo "Fetching project ID..."
          PROJECT_ID=8  # Directly use the known project ID
          echo "Project ID: $PROJECT_ID"

          ISSUE_URL=$(curl -s -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER | jq -r '.html_url')
          COLUMNS_URL=https://api.github.com/projects/$PROJECT_ID/columns

          echo "Fetching available columns from: $COLUMNS_URL"
          AVAILABLE_COLUMNS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.inertia-preview+json" $COLUMNS_URL | jq -r '.[] | .name')

          echo "Available columns:"
          echo "$AVAILABLE_COLUMNS"

          COLUMN_ID=$(curl -s -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.inertia-preview+json" $COLUMNS_URL | jq -r --arg STATUS "$STATUS" '.[] | select(.name == $STATUS) | .id')

          if [ -z "$COLUMN_ID" ]; then
            echo "Column $STATUS not found in the project."
            exit 1
          fi

          curl -X POST -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.inertia-preview+json" https://api.github.com/projects/columns/$COLUMN_ID/cards -d "{\"content_url\":\"$ISSUE_URL\"}"
