name: Check Project Assignment on Label Change

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  check-project-assignment:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up jq
        run: sudo apt-get install jq

      - name: Get Projects
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPO=${{ github.repository }}
          ISSUE_NUMBER=$([[ "${{ github.event_name }}" == "issues" ]] && echo "${{ github.event.issue.number }}" || echo "${{ github.event.pull_request.number }}")
          ISSUE_TYPE=$([[ "${{ github.event_name }}" == "issues" ]] && echo "issues" || echo "pulls")

          echo "Fetching projects for repository..."
          PROJECTS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.inertia-preview+json" https://api.github.com/repos/$REPO/projects)
          echo "Projects: $PROJECTS"

          echo "$PROJECTS" | jq -c '.[]' | while read project; do
            PROJECT_ID=$(echo "$project" | jq -r '.id')
            PROJECT_NAME=$(echo "$project" | jq -r '.name')

            echo "Fetching columns for project $PROJECT_NAME..."
            COLUMNS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.inertia-preview+json" https://api.github.com/projects/$PROJECT_ID/columns)
            echo "Columns: $COLUMNS"

            echo "$COLUMNS" | jq -c '.[]' | while read column; do
              COLUMN_ID=$(echo "$column" | jq -r '.id')
              COLUMN_NAME=$(echo "$column" | jq -r '.name')

              echo "Checking cards in column $COLUMN_NAME..."
              CARDS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.inertia-preview+json" https://api.github.com/projects/columns/$COLUMN_ID/cards)
              echo "Cards: $CARDS"

              CARD_URL=$(echo "$CARDS" | jq -r --arg ISSUE_URL "https://api.github.com/repos/$REPO/$ISSUE_TYPE/$ISSUE_NUMBER" '.[] | select(.content_url == $ISSUE_URL) | .content_url')

              if [ -n "$CARD_URL" ]; then
                echo "Issue/PR found in project $PROJECT_NAME (ID: $PROJECT_ID), column $COLUMN_NAME"
                exit 0
              fi
            done
          done
