# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

Fetching issue details...
Issue Details: {
  "url": "https://api.github.com/repos/TheNewestFactor/effective-meme/issues/4",
  "repository_url": "https://api.github.com/repos/TheNewestFactor/effective-meme",
  "labels_url": "https://api.github.com/repos/TheNewestFactor/effective-meme/issues/4/labels{/name}",
  "comments_url": "https://api.github.com/repos/TheNewestFactor/effective-meme/issues/4/comments",
  "events_url": "https://api.github.com/repos/TheNewestFactor/effective-meme/issues/4/events",
  "html_url": "https://github.com/TheNewestFactor/effective-meme/issues/4",
  "id": 2483025799,
  "node_id": "I_kwDOI3l-Bc6T__eH",
  "number": 4,
  "title": "Look here",
  "user": {
    "login": "OptimisticImpulse",
    "id": 111015172,
    "node_id": "U_kgDOBp31BA",
    "avatar_url": "https://avatars.githubusercontent.com/u/111015172?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/OptimisticImpulse",
    "html_url": "https://github.com/OptimisticImpulse",
    "followers_url": "https://api.github.com/users/OptimisticImpulse/followers",
    "following_url": "https://api.github.com/users/OptimisticImpulse/following{/other_user}",
    "gists_url": "https://api.github.com/users/OptimisticImpulse/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/OptimisticImpulse/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/OptimisticImpulse/subscriptions",
    "organizations_url": "https://api.github.com/users/OptimisticImpulse/orgs",
    "repos_url": "https://api.github.com/users/OptimisticImpulse/repos",
    "events_url": "https://api.github.com/users/OptimisticImpulse/events{/privacy}",
    "received_events_url": "https://api.github.com/users/OptimisticImpulse/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 7366246679,
      "node_id": "LA_kwDOI3l-Bc8AAAABtxABFw",
      "url": "https://api.github.com/repos/TheNewestFactor/effective-meme/labels/feature-request",
      "name": "feature-request",
      "color": "2319E0",
      "default": false,
      "description": ""
    }
  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 0,
  "created_at": "2024-08-23T12:21:15Z",
  "updated_at": "2024-08-23T13:07:02Z",
  "closed_at": null,
  "author_association": "COLLABORATOR",
  "active_lock_reason": null,
  "body": "Work already!",
  "closed_by": null,
  "reactions": {
    "url": "https://api.github.com/repos/TheNewestFactor/effective-meme/issues/4/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/TheNewestFactor/effective-meme/issues/4/timeline",
  "performed_via_github_app": null,
  "state_reason": null
}
Fetching available columns from: https://api.github.com/projects/4905915/columns
Available columns response: [

]
Column Enhancement not found in the project.
Error: Process completed with exit code 1.
