name: Check Project Assignment on Label Change

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  check-project-assignment:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up jq
        run: sudo apt-get install jq

      - name: Get Project Details
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PROJECT_ID=4905915
          REPO=${{ github.repository }}
          ISSUE_NUMBER=$([[ "${{ github.event_name }}" == "issues" ]] && echo "${{ github.event.issue.number }}" || echo "${{ github.event.pull_request.number }}")
          ISSUE_TYPE=$([[ "${{ github.event_name }}" == "issues" ]] && echo "issues" || echo "pulls")

          echo "Fetching columns for project $PROJECT_ID..."
          COLUMNS_RESPONSE=$(curl -s -w "%{http_code}" -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.inertia-preview+json" https://api.github.com/projects/$PROJECT_ID/columns)
          COLUMNS_HTTP_STATUS=$(echo "$COLUMNS_RESPONSE" | tail -n1)
          COLUMNS=$(echo "$COLUMNS_RESPONSE" | head -n-1)
          echo "Columns HTTP Status: $COLUMNS_HTTP_STATUS"
          echo "Columns: $COLUMNS"

          if [ "$COLUMNS_HTTP_STATUS" -ne 200 ]; then
            echo "Failed to fetch columns for project $PROJECT_ID. Please check the token permissions and API endpoint."
            exit 1
          fi

          echo "$COLUMNS" | jq -c '.[]' | while read column; do
            COLUMN_ID=$(echo "$column" | jq -r '.id')
            COLUMN_NAME=$(echo "$column" | jq -r '.name')

            echo "Checking cards in column $COLUMN_NAME..."
            CARDS_RESPONSE=$(curl -s -w "%{http_code}" -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.inertia-preview+json" https://api.github.com/projects/columns/$COLUMN_ID/cards)
            CARDS_HTTP_STATUS=$(echo "$CARDS_RESPONSE" | tail -n1)
            CARDS=$(echo "$CARDS_RESPONSE" | head -n-1)
            echo "Cards HTTP Status: $CARDS_HTTP_STATUS"
            echo "Cards: $CARDS"

            if [ "$CARDS_HTTP_STATUS" -ne 200 ]; then
              echo "Failed to fetch cards for column $COLUMN_NAME. Please check the token permissions and API endpoint."
              continue
            fi

            CARD_URL=$(echo "$CARDS" | jq -r --arg ISSUE_URL "https://api.github.com/repos/$REPO/$ISSUE_TYPE/$ISSUE_NUMBER" '.[] | select(.content_url == $ISSUE_URL) | .content_url')

            if [ -n "$CARD_URL" ]; then
              echo "Issue/PR found in project column $COLUMN_NAME"
              exit 0
            fi
          done
